from langchain_core.prompts import PromptTemplate
from typing  import Literal
from langgraph.graph import END

from graph.State import SQLAgentState
from models.llm import model_creation
from models.query_validation import Query_evaluation
from langgraph.types import Command

def remediate_sql(state:SQLAgentState)-> Command[Literal["query_execution","error_router",END]]:
    try:
        if(state["retry_count"]==2):
            print("retry count exceeded")
            return Command(
                update={"result":"unable to process these sql request",
                        "Error":"we cant process this sql request"},
                goto=END
            )
       
        sql_correction_prompt = PromptTemplate.from_template("""
                You are an expert SQL developer.
        
                A SQL query generated by another AI failed to execute.
        
                Your task is to analyze the database error, understand why the query failed, and generate a corrected SQL query.
        
                Rules:
                - Use ONLY the tables and columns provided in the schema.
                - Do NOT invent table names or column names.
                - Preserve the original intent of the user's request.
                - Return ONLY the corrected SQL query.
                - Do NOT include explanations, markdown, or code fences.
        
                =========================
                User Request
                =========================
                {user_request}
        
                =========================
                Database Schema
                =========================
                {schema}
        
                =========================
                Generated SQL
                =========================
                {generated_sql}
        
                =========================
                Database Error
                =========================
                {database_error}
                """)
        sql_correction_prompt = sql_correction_prompt.format(
                    user_request=state["input"],
                    schema=state["schema"],
                    generated_sql=state["query"],
                    database_error=state["database_error"]
                )

        print("sql_correction_prompt:",sql_correction_prompt)
        model=model_creation().with_structured_output(Query_evaluation)
        data=model.invoke(sql_correction_prompt)
        query=data.query
        print("remediated query:",query)
        return Command(
                            update={"query":query,
                            "retry_count":state["retry_count"]+1},
                            goto="query_execution"
                        )
    except:
        return Command(
                        update={"Error":"error at remediate_sql"},
                        goto="error_router"
                    )